export const ErrorCodes = {
  FILE_INVALID: "FILE_INVALID",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_TYPE_UNSUPPORTED: "FILE_TYPE_UNSUPPORTED",
  PDF_CORRUPTED: "PDF_CORRUPTED",
  PDF_PASSWORD_PROTECTED: "PDF_PASSWORD_PROTECTED",
  PAGE_RENDER_FAILED: "PAGE_RENDER_FAILED",
  OCR_FAILED: "OCR_FAILED",
  OCR_AUTH_ERROR: "OCR_AUTH_ERROR",
  OCR_BUCKET_ACCESS_ERROR: "OCR_BUCKET_ACCESS_ERROR",
  OCR_SUBMISSION_FAILED: "OCR_SUBMISSION_FAILED",
  OCR_OPERATION_TIMEOUT: "OCR_OPERATION_TIMEOUT",
  OCR_OPERATION_FAILED: "OCR_OPERATION_FAILED",
  OCR_OUTPUT_MISSING: "OCR_OUTPUT_MISSING",
  OCR_OUTPUT_PARSE_FAILED: "OCR_OUTPUT_PARSE_FAILED",
  OCR_INVALID_DOCUMENT: "OCR_INVALID_DOCUMENT",
  OCR_GCS_UPLOAD_FAILED: "OCR_GCS_UPLOAD_FAILED",
  OCR_GCS_DOWNLOAD_FAILED: "OCR_GCS_DOWNLOAD_FAILED",
  OCR_CONFIGURATION_ERROR: "OCR_CONFIGURATION_ERROR",
  QUESTION_EXTRACTION_FAILED: "QUESTION_EXTRACTION_FAILED",
  ANSWER_EXTRACTION_FAILED: "ANSWER_EXTRACTION_FAILED",
  MODEL_UNAVAILABLE: "MODEL_UNAVAILABLE",
  MODEL_TIMEOUT: "MODEL_TIMEOUT",
  MODEL_OUTPUT_INVALID: "MODEL_OUTPUT_INVALID",
  MAPPING_FAILED: "MAPPING_FAILED",
  LOCALIZATION_FAILED: "LOCALIZATION_FAILED",
  VIEWER_ERROR: "VIEWER_ERROR",
  STORAGE_ERROR: "STORAGE_ERROR",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  INVALID_STAGE_TRANSITION: "INVALID_STAGE_TRANSITION",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class AppError extends Error {
  code: ErrorCode;
  stage?: string;
  details?: unknown;
  constructor(code: ErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.details = details;
  }
}
