import * as fs from 'fs'; import * as path from 'path'; import * as os from 'os'; import { parseQuestionsFromTextract } from '@/lib/structure/question-parser';
const jobId='39ac494f-ecec-4ccc-91ca-c9e9995a644b';
const p = path.join(os.tmpdir(),'veda-ai',jobId,'debug','questionPaper-textract.json');
const ocr = JSON.parse(fs.readFileSync(p,'utf8'));
const pages = ocr.pages.map((pg:any,i:number)=>({id:`page-${pg.pageNumber}`, documentId:'d1', pageNumber: pg.pageNumber, width:800, height:1100, rotation:0}));
const res = parseQuestionsFromTextract(ocr, pages);
console.log('total',res.length,'top',res.filter(r=>r.depth===0).length);
res.forEach((r:any)=> console.log(`${r.normalizedNumber} depth=${r.depth} parent=${r.parent||''} opts=${r.options?.length||0} text=${r.text.slice(0,60).replace(/\n/g,' ')}`));
const q36 = res.find((r:any)=>r.normalizedNumber==='36');
console.log('Q36',q36);
const q36subs = res.filter((r:any)=>r.parent==='36' || r.normalizedNumber.startsWith('36('));
console.log('36 subs',q36subs.map((r:any)=>r.normalizedNumber));
const q37 = res.find((r:any)=>r.normalizedNumber==='37');
console.log('Q37',q37?.normalizedNumber, q37?.depth);
const q37subs = res.filter((r:any)=>r.normalizedNumber.startsWith('37('));
console.log('37 subs',q37subs.map((r:any)=>r.normalizedNumber));
const q38 = res.find((r:any)=>r.normalizedNumber==='38');
console.log('Q38',q38);
const q38subs = res.filter((r:any)=>r.normalizedNumber.startsWith('38('));
console.log('38 subs',q38subs.map((r:any)=>r.normalizedNumber));
